// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef {{header_guard_def}}
#define {{header_guard_def}}

#ifdef __cplusplus
extern "C" {
#endif

{%- if ds.linux_kernel %}
#include <linux/types.h>
{%- else %}
#include <stdint.h>
{%- endif %}
{%- if ds.linux_kernel %}
#include <linux/build_bug.h>
{%- elif ds.std.static_assert_needs_assert_h %}
#include <assert.h>
{%- endif %}
